version: "3.7"

services:
  ts-node-docker:
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    image: rcp/ts-node:latest
    network_mode: "host"
    container_name: rcp-ts-node
